### ISSUE TITLE
mocks : add a timeout before sending back datas to simulate network latency

### ISSUE THREAD

**Issue by mvidailhet** [sandorfr/gulp-swagger-generator#11]
It would be great to have this timeout to be able to test app loading properly.

**Comment by sandorfr** [comment]
a first version is available more control over it will be added later with #9
add

```
mock: {
    delay: 2000
}
```

to the template options

**Comment by mvidailhet** [comment]
awesome !

**Comment by sandorfr** [comment]
see #23
