### ISSUE TITLE
SPIRIT ADP: ajouter responseType: 'arraybuffer' à 3 méthodes dans web api

### ISSUE THREAD

**Issue by jondxs** [sandorfr/gulp-swagger-generator#24]
Bonjour Cyprien,

Nous avons 3 web methods dans l'api qui retournent un fichier .xlsx. Nous avons trouvé que ces fichiers sont corrompus côté client. Pour résoudre le problème, il a fallu ajouter responseType: 'arraybuffer' dans le fichier SpiritClient.ts, qui est normalement autogéneré par swagger/gulp. Il faut modifier les 3 méthodes dans le webAPI pour que ces settings soient autogénerés.

les 3 méthodes dans SpiritClient sont:
`
//Export Detail Couts Réels

```
/**
* 
* @param { string } details Données à exporter
* @param { string } idAffaire 
* @param { number } idEntiteContributrice Identificateur de l'entité contributrice à supprimer
* @return { any } 
*/
getApiAffaireByIdAffaireEntiteContributriceByIdEntiteContributriceDetail(
    args: IGetApiAffaireByIdAffaireEntiteContributriceByIdEntiteContributriceDetailArgs,
    canceller?: angular.IDeferred<any>
) : angular.IHttpPromise<Object> {

    var uri = this.baseUri + '/api/Affaire/' + String(args.idAffaire) + '/EntiteContributrice/' + String(args.idEntiteContributrice) + '/Detail';

    var httpRequestParams: any = {
        method: 'GET',
        url: uri,
        json: true,
        responseType: 'arraybuffer',
        params: {
            'details': args.details
        },
        headers: {
        }
    };
    if (canceller){
        httpRequestParams.timeout = canceller.promise;
    }

    httpRequestParams = this.authenticateService.configureRequest(httpRequestParams); 
}
```

// Export Affaire/

```
/**
* 
* @param { number } idAffaire Identifiant de l'affaire
* @return { any } 
*/
getApiAffaireByIdAffaireFraisExport(
    args: IGetApiAffaireByIdAffaireFraisExportArgs,
    canceller?: angular.IDeferred<any>
) : angular.IHttpPromise<Object> {
     var uri = this.baseUri + '/api/Affaire/' + String(args.idAffaire) + '/Frais/Export'; 
    var httpRequestParams: any = {
        method: 'GET',
        url: uri,
        json: true,
        responseType: 'arraybuffer',
        params: {
        },
        headers: {
        }
    };
    if (canceller){
        httpRequestParams.timeout = canceller.promise;
    }    
    httpRequestParams = this.authenticateService.configureRequest(httpRequestParams);    
    return this.$http(httpRequestParams);
}
```

//Export Echéancier

/**
- 
- @param { number } idEntiteContributrice Identifiant de l'entité contributrice
- @return { any } 
  */
  getApiAffaireEntiteCByIdEntiteContributriceEcheancierExport(
  args: IGetApiAffaireEntiteCByIdEntiteContributriceEcheancierExportArgs,
  canceller?: angular.IDeferred
  ) : angular.IHttpPromise {
  
  ```
  var uri = this.baseUri + '/api/Affaire/EntiteC/' + String(args.idEntiteContributrice) + '/Echeancier/Export';    
  var httpRequestParams: any = {
      method: 'GET',
      url: uri,
      json: true,
      responseType: 'arraybuffer',
      params: {
      },
      headers: {
      }
  };    
  if (canceller){
      httpRequestParams.timeout = canceller.promise;
  }    
  httpRequestParams = this.authenticateService.configureRequest(httpRequestParams);    
  return this.$http(httpRequestParams);
  ```
  
  }`
  et côté api:
  ///

/// Exporter onglet CFE vers Excel
///

/// Identifiant de l'affaire
/// fichier Excel
[Route("{idAffaire:int}/Frais/Export"), HttpGet]
public HttpResponseMessage ExportCfeToExcel(int idAffaire)
{
var rsp = this.affaireRules.ExporterCFE(idAffaire);
return rsp;
}
    /// <summary>

    /// Exporter l'échéancier
    /// </summary>

    /// <param name="idEntiteContributrice">Identifiant de l'entité contributrice</param>
    /// <returns>Fichier Excel contenant l'échéancier</returns>
    [Route("{idEntiteContributrice}/Echeancier/Export"),  HttpGet]
    public HttpResponseMessage ExportEcheancier(int idEntiteContributrice)
    {
///

/// Export des données de détailConsommation
///

/// Données à exporter
/// Identificateur de l'entité contributrice à supprimer
/// Fichier excel exporté
[Route("{idEntiteContributrice:int}/Detail"), HttpGet]
public HttpResponseMessage ExporterDetailConsommation(string details, int idEntiteContributrice)
{
return this.entiteContributriceRules.ExportCreation(details, idEntiteContributrice);
}

**Comment by sandorfr** [comment]
You need to make sure your swagger definition exposes the right content types and update gulp-swagger-generator to latest version
