### ISSUE TITLE
Is it possible to set scheme from gulp the same way as host?

### ISSUE THREAD

**Issue by stombeur** [sandorfr/gulp-swagger-generator#27]
this works
`host: {
                    set: "MyConfig.Api.Host",
                }`
provided that the type MyConfig is injected

but this doesn't work
`scheme: {
                    set: "MyConfig.Api.Scheme",
                }`

is this by design?

I'm more than willing to create a PR if needed, but I'm not sure where to start looking.

**Comment by sandorfr** [comment]
Not atm, but that's definitely something which should be possible. I'll take a look tonight.

However you can override the default scheme using this option :  `scheme: 'https',`. It can help you as a temporary workaround.

Regarding PRs, I'm currently reworking the whole thing to separate gulp from the core library and have more flexible naming policies (both for operation and types), I think it will be easier to contribute after that.

**Comment by stombeur** [comment]
would this be enough to make it work?

in [Client.hbs](https://github.com/sandorfr/gulp-swagger-generator/blob/master/lib%2Ftemplates%2Ftypescript%2Fangular%2FClient.hbs)
on line 20, after the line starting with this.scheme... add the following (like the host.set above)

`{{#options.scheme.set}}
        if ({{.}}) {
            this.scheme = {{.}};
        }
        {{/options.scheme.set}}`

I'm not familiar with building npm packages, so I can't easily test it. If I have the time tonight, I'll give it a shot.

**Comment by sandorfr** [comment]
yes this should do the trick but it would conflict with the basic override. You can test this
https://github.com/sandorfr/gulp-swagger-generator/blob/feature/angular-optional-namespace/lib/templates/typescript/angular/Client.hbs
available on nuget under version : 0.1.0-angular-optional-namespace.2

**Comment by stombeur** [comment]
Wow, thanks!

But I think there is a small typo in there:

``` javascript
this.scheme = '{{#options.scheme.override}}{{.}}{{/options.scheme.override}}{{#unless options.scheme.override}}'http'{{/unless}}';
```

should probably be http and not 'http' -> the generated code is like this:

``` javascript
this.scheme = ''http'';   // this has two ' front and back
if (MyConfig.Api.Scheme) {  
   this.scheme = MyConfig.Api.Scheme;  
}
```

but I've already taken too much of your time. I have a working solution with a gulp variable depending on the environment, so don't create a new version on my behalf or something.

thanks a million for this package btw! It saves me from writing yet-another-codegenerator.

**Comment by sandorfr** [comment]
You are right :( I'll fix this later. In the meantime you can workaround this by setting both override and set in your options.

**Comment by krizic** [comment]
I really looking forward to see this.scheme = ''http'';  fixed. Can I pull request for this?

**Comment by sandorfr** [comment]
@krizic yes sure

**Comment by sandorfr** [comment]
@mvidailhet @asiffermann have you taken that into account in the new template?

**Comment by mvidailhet** [comment]
@sandorfr Yes, I saw this typo while working on the Angular1 version. It works perfectly now :)
