### ISSUE TITLE
error : Path must be a string

### ISSUE THREAD

**Issue by saeedmsdi** [sandorfr/gulp-swagger-generator#39]
Hi

The content of gulpfile.js

`var gulp = require("gulp"),
    path = require("path"),
    swaggerGenerator = require('gulp-swagger-generator'),
    rename = require("gulp-rename");
 
gulp.task('default', function () {
    return gulp.src('./swagger.json')
        .pipe(swaggerGenerator({
            clientName: 'ServiceClient',
            templateOptions: {
                module: "Sample",
                scheme: 'http',
            },
            template: "csharp-netstandard-1.3",
            singleFile: true
        }))
        .pipe(rename("serviceClient.ts"))
        .pipe(gulp.dest("./src/app/services/"));
});`

But I get this error when i run >gulp : 

`(node:16901) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Path must be a string. Received undefined
(node:16901) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Node : 7.9
npm : 4.5
gulp 3.9.1
OS : osx 10.12.4 Sierra

**Comment by sandorfr** [comment]
Hi, 
Thank you for reporting this issue. From what I see you are using the legacy version (current "stable"). However it does not provide a netstandard template. We have a netstandard template actively being developed on the new version of the generator. It is documented here : https://github.com/geeklearningio/gl-swagger-generator/wiki . 

```json
var gulp = require("gulp"),
    path = require("path"),
    swaggerGenerator = require('gulp-swagger-generator'),
    remoteSrc = require('gulp-remote-src'),
    rename = require("gulp-rename");

function generate() {
    return gulp.src('./api-swagger.json')
        .pipe(swaggerGenerator({
            "language": "csharp",
            "framework": "netstandard",
            "version": "1.3",
            "mode": "project",
            "dependencies": {
            },
            "mediaTypesPriorities": {
                "application/json": 1
            },
            "ambientTypes": [
            ],
            "templateOptions": {
                "clientName": "AClient",
                "projectGuid": "51c44871-da5d-41ef-90e8-81611bd3aa30",
                "rootNamespace": "MyNamespace.Client",
                "operation": {
                    "onError": {
                        "useOkSchema": true
                    }
                }
            }
        }))
        .pipe(gulp.dest("../MyNamespace.Client"));
}


gulp.task('swagger:generate', generate);
```

This will generate a project (project.json based ATM).

**Comment by sandorfr** [comment]
Hi 
FYI, We've published an update to the new version of the generator with both .net standard and angular 1.5 support.
Hope this helps.
